### ISSUE TITLE
overlapping month headings in activity map.

### ISSUE THREAD

**Issue by co16353sidak** [nataliemarleny/nataliemarleny.github.io#1]
The activity map which cleverly shows your attended events (an amazing idea by the way) has an issue where in the months `feb` and `mar` seem to have been merged together.
I have included a screenshot for the same,

<img width="458" alt="Screenshot 2019-04-22 at 11 43 09 PM" src="https://user-images.githubusercontent.com/35738138/56516683-c0f01e00-6558-11e9-8a8b-1baa1a3b3140.png">

Although I don't have an idea as to how this will be fixed, I will be interested in working on this. 🥇 

P.S: just reading through the whole resume was amazing, nice job. 👍

**Comment by nataliemarleny** [comment]
@co16353sidak - thanks for this thoughtful issue.

The activity map is forked from [DKirwan's calendar heatmap project](https://github.com/DKirwan/calendar-heatmap) which is currently not under active maintenance. 

My personal site is currently undergoing a migration to a new stack, and this will be something I'll be sure to be mindful of in the next iteration.
